//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        public int cod { get; set; }

        [Required(ErrorMessage = "O nome do usuário é obrigatório", AllowEmptyStrings = false)]
        public string nome { get; set; }

        [Required(ErrorMessage = "O sobrenome do usuário é obrigatório", AllowEmptyStrings = false)]
        public string sobrenome { get; set; }

        [Required(ErrorMessage = "O CPF do usuário é obrigatório", AllowEmptyStrings = false)]
        public Nullable<long> cpf { get; set; }

        public string cpf_formatado { get; set; }

        [Required(ErrorMessage = "Informe o seu email")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
        public string email { get; set; }

        [Required(ErrorMessage = "O login do usuário é obrigatório", AllowEmptyStrings = false)]
        public string loginUsuario { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "A senha do usuário é obrigatória", AllowEmptyStrings = false)]
        public string senha { get; set; }

        [Required(ErrorMessage = "O status do usuário é obrigatório", AllowEmptyStrings = false)]
        public bool stAtivo { get; set; }
    }
}
